# Generated by Django 5.2.8 on 2025-11-07 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digilocker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='running_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_running', models.BooleanField(default=False)),
            ],
        ),
    ]
